In [24]:
from pathlib import Path

In [25]:
alljoined_base = Path(
    "/kreka/research/willy/side/alljoined"
)

In [26]:
first_block = alljoined_base / "raw_eeg/sub-01/session_01/block_01/"

In [27]:
import mne

In [28]:
edf_file = first_block / 'Subject 1, Session 1, Block 1 Recording_FLEX2_213075_2025.01.25T15.18.28.08.00.md.edf'

In [29]:
edf_file

PosixPath('/kreka/research/willy/side/alljoined/raw_eeg/sub-01/session_01/block_01/Subject 1, Session 1, Block 1 Recording_FLEX2_213075_2025.01.25T15.18.28.08.00.md.edf')

In [30]:
raw_data = mne.io.read_raw_edf(edf_file)
raw_data

Extracting EDF parameters from /kreka/research/willy/side/alljoined/raw_eeg/sub-01/session_01/block_01/Subject 1, Session 1, Block 1 Recording_FLEX2_213075_2025.01.25T15.18.28.08.00.md.edf...
Setting channel info structure...
Creating raw.info structure...


<RawEDF | Subject 1, Session 1, Block 1 Recording_FLEX2_213075_2025.01.25T15.18.28.08.00.md.edf, 127 x 76032 (297.0 s), ~99 KiB, data not loaded>

In [8]:
type(raw_data)

mne.io.edf.edf.RawEDF

In [9]:
dir(raw_data)

['__class__',
 '__contains__',
 '__del__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_annotations',
 '_cals',
 '_check_bad_segment',
 '_comp',
 '_cropped_samp',
 '_dtype',
 '_dtype_',
 '_extra_attributes',
 '_filenames',
 '_first_samps',
 '_first_time',
 '_get_buffer_size',
 '_get_channel_positions',
 '_get_duration_string',
 '_getitem',
 '_handle_tmin_tmax',
 '_init_kwargs',
 '_last_samps',
 '_last_time',
 '_orig_units',
 '_parse_get_set_params',
 '_pick_drop_channels',
 '_pick_projs',
 '_preload_data',
 '_projector',
 '_raw_extras',
 '_raw_le

In [10]:
raw_data.ch_names

['TimestampS',
 'TimestampMs',
 'OrTimestampS',
 'OrTimestampMs',
 'Counter',
 'Interpolated',
 'Cz',
 'FCz',
 'Afz',
 'Fp1',
 'F5',
 'F1',
 'CP5',
 'CP3',
 'CP1',
 'P1',
 'P3',
 'P5',
 'P7',
 'PO7',
 'PO3',
 'O1',
 'Pz',
 'POz',
 'Oz',
 'O2',
 'PO4',
 'PO8',
 'P8',
 'P6',
 'P4',
 'P2',
 'CP2',
 'CP4',
 'CP6',
 'F2',
 'F6',
 'Fp2',
 'RawCq',
 'Battery',
 'BatteryPercent',
 'FwBufferSize',
 'FwClockTime',
 'MarkerHardware',
 'CQ.Cz',
 'CQ.FCz',
 'CQ.Afz',
 'CQ.Fp1',
 'CQ.F5',
 'CQ.F1',
 'CQ.CP5',
 'CQ.CP3',
 'CQ.CP1',
 'CQ.P1',
 'CQ.P3',
 'CQ.P5',
 'CQ.P7',
 'CQ.PO7',
 'CQ.PO3',
 'CQ.O1',
 'CQ.Pz',
 'CQ.POz',
 'CQ.Oz',
 'CQ.O2',
 'CQ.PO4',
 'CQ.PO8',
 'CQ.P8',
 'CQ.P6',
 'CQ.P4',
 'CQ.P2',
 'CQ.CP2',
 'CQ.CP4',
 'CQ.CP6',
 'CQ.F2',
 'CQ.F6',
 'CQ.Fp2',
 'CQ.Overall',
 'EQ.SampleRateQua',
 'EQ.OVERALL',
 'EQ.Cz',
 'EQ.FCz',
 'EQ.Afz',
 'EQ.Fp1',
 'EQ.F5',
 'EQ.F1',
 'EQ.CP5',
 'EQ.CP3',
 'EQ.CP1',
 'EQ.P1',
 'EQ.P3',
 'EQ.P5',
 'EQ.P7',
 'EQ.PO7',
 'EQ.PO3',
 'EQ.O1',
 'EQ.Pz',
 'EQ.POz'

In [11]:
mne.channels.make_standard_montage('standard_1020')

<DigMontage | 0 extras (headshape), 0 HPIs, 3 fiducials, 94 channels>

In [12]:
raw_data.set_montage(mne.channels.make_standard_montage("standard_1020"))

ValueError: DigMontage is only a subset of info. There are 96 channel positions not present in the DigMontage. The channels missing from the montage are:

['TimestampS', 'TimestampMs', 'OrTimestampS', 'OrTimestampMs', 'Counter', 'Interpolated', 'Afz', 'RawCq', 'Battery', 'BatteryPercent', 'FwBufferSize', 'FwClockTime', 'MarkerHardware', 'CQ.Cz', 'CQ.FCz', 'CQ.Afz', 'CQ.Fp1', 'CQ.F5', 'CQ.F1', 'CQ.CP5', 'CQ.CP3', 'CQ.CP1', 'CQ.P1', 'CQ.P3', 'CQ.P5', 'CQ.P7', 'CQ.PO7', 'CQ.PO3', 'CQ.O1', 'CQ.Pz', 'CQ.POz', 'CQ.Oz', 'CQ.O2', 'CQ.PO4', 'CQ.PO8', 'CQ.P8', 'CQ.P6', 'CQ.P4', 'CQ.P2', 'CQ.CP2', 'CQ.CP4', 'CQ.CP6', 'CQ.F2', 'CQ.F6', 'CQ.Fp2', 'CQ.Overall', 'EQ.SampleRateQua', 'EQ.OVERALL', 'EQ.Cz', 'EQ.FCz', 'EQ.Afz', 'EQ.Fp1', 'EQ.F5', 'EQ.F1', 'EQ.CP5', 'EQ.CP3', 'EQ.CP1', 'EQ.P1', 'EQ.P3', 'EQ.P5', 'EQ.P7', 'EQ.PO7', 'EQ.PO3', 'EQ.O1', 'EQ.Pz', 'EQ.POz', 'EQ.Oz', 'EQ.O2', 'EQ.PO4', 'EQ.PO8', 'EQ.P8', 'EQ.P6', 'EQ.P4', 'EQ.P2', 'EQ.CP2', 'EQ.CP4', 'EQ.CP6', 'EQ.F2', 'EQ.F6', 'EQ.Fp2', 'MOT.TimestampS', 'MOT.TimestampMs', 'MOT.OrTimestampS', 'MOT.OrTimestampM', 'MOT.CounterMems', 'MOT.Interpolated', 'MOT.Q0', 'MOT.Q1', 'MOT.Q2', 'MOT.Q3', 'MOT.AccX', 'MOT.AccY', 'MOT.AccZ', 'MOT.MagX', 'MOT.MagY', 'MOT.MagZ'].

Consider using inst.rename_channels to match the montage nomenclature, or inst.set_channel_types if these are not EEG channels, or use the on_missing parameter if the channel positions are allowed to be unknown in your analyses.

In [ ]:
raw_

In [22]:
type(raw_data)

NameError: name 'raw_data' is not defined

In [23]:
import sys
from pathlib import Path
sys.path.append(
    str(Path.cwd().parent)
)
import importlib
import utils
importlib.reload(utils)

<module 'utils' from '/kreka/research/willy/side/brain/utils.py'>

In [15]:
raw_data.info

<Info | 8 non-empty values
 bads: []
 ch_names: TimestampS, TimestampMs, OrTimestampS, OrTimestampMs, Counter, ...
 chs: 127 EEG
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 128.0 Hz
 meas_date: 2025-01-25 15:18:28 UTC
 nchan: 127
 projs: []
 sfreq: 256.0 Hz
 subject_info: <subject_info | his_id: X, sex: 0, last_name: X>
>

In [16]:
rec_data, rec_mask = utils.mne_to_tensor(
    raw_data,
    normalize="recording"
)

raw data shape torch.Size([127, 76032])
Skipping channel: TimestampS
Skipping channel: TimestampMs
Skipping channel: OrTimestampS
Skipping channel: OrTimestampMs
Skipping channel: Counter
Skipping channel: Interpolated
Skipping channel: RawCq
Skipping channel: Battery
Skipping channel: BatteryPercent
Skipping channel: FwBufferSize
Skipping channel: FwClockTime
Skipping channel: MarkerHardware
Skipping channel: CQ.Cz
Skipping channel: CQ.FCz
Skipping channel: CQ.Afz
Skipping channel: CQ.Fp1
Skipping channel: CQ.F5
Skipping channel: CQ.F1
Skipping channel: CQ.CP5
Skipping channel: CQ.CP3
Skipping channel: CQ.CP1
Skipping channel: CQ.P1
Skipping channel: CQ.P3
Skipping channel: CQ.P5
Skipping channel: CQ.P7
Skipping channel: CQ.PO7
Skipping channel: CQ.PO3
Skipping channel: CQ.O1
Skipping channel: CQ.Pz
Skipping channel: CQ.POz
Skipping channel: CQ.Oz
Skipping channel: CQ.O2
Skipping channel: CQ.PO4
Skipping channel: CQ.PO8
Skipping channel: CQ.P8
Skipping channel: CQ.P6
Skipping channel:

In [17]:
rec_data.shape

torch.Size([297, 354, 256])

In [18]:
rec_mask.shape

torch.Size([354])

In [20]:
rec_data[1][1]

tensor([ 0.8518,  0.6149,  0.3964,  0.3688,  0.5850,  0.9184,  1.1645,  1.1898,
         1.0081,  0.7437,  0.5597,  0.5666,  0.7598,  1.0081,  1.1484,  1.0863,
         0.8518,  0.5758,  0.4217,  0.4746,  0.7092,  0.9966,  1.1760,  1.1507,
         0.9598,  0.7414,  0.6517,  0.7276,  0.8701,  0.9276,  0.8173,  0.5942,
         0.4056,  0.3665,  0.4999,  0.7322,  0.9460,  1.0380,  0.9805,  0.8035,
         0.5965,  0.4539,  0.4447,  0.5689,  0.7644,  0.9230,  0.9575,  0.8494,
         0.6494,  0.4723,  0.4125,  0.4838,  0.5896,  0.6057,  0.4838,  0.3090,
         0.2354,  0.3274,  0.5114,  0.6149,  0.5022,  0.1963, -0.1142, -0.1832,
         0.0951,  0.5988,  1.0265,  1.1070,  0.7897,  0.2975, -0.0268,  0.0376,
         0.4332,  0.8770,  1.0610,  0.8587,  0.3918, -0.0659, -0.2614, -0.1326,
         0.1664,  0.3688,  0.3228,  0.0951, -0.0935, -0.0682,  0.1756,  0.4861,
         0.6908,  0.7184,  0.6264,  0.5114,  0.4516,  0.4700,  0.5344,  0.5896,
         0.5643,  0.4240,  0.1986, -0.01

In [21]:
from utils import CHANNEL_TO_IDX
IDX_TO_CHANNEL = {
    v:k
    for k,v in CHANNEL_TO_IDX.items()
}
IDX_TO_CHANNEL

{0: 'NZ',
 1: 'FP1',
 2: 'FPZ',
 3: 'FP2',
 4: 'AFP1',
 5: 'AFP2',
 6: 'AFP3H',
 7: 'AFP4H',
 8: 'AF9',
 9: 'AF7',
 10: 'AF5',
 11: 'AF3',
 12: 'AF1',
 353: 'AFZ',
 14: 'AF2',
 15: 'AF4',
 16: 'AF6',
 17: 'AF8',
 18: 'AF10',
 19: 'AF9H',
 20: 'AF7H',
 21: 'AF5H',
 22: 'AF3H',
 23: 'AF1H',
 24: 'AF2H',
 25: 'AF4H',
 26: 'AF6H',
 27: 'AF8H',
 28: 'AF10H',
 29: 'AFF9',
 30: 'AFF7',
 31: 'AFF5',
 32: 'AFF3',
 33: 'AFF1',
 34: 'AFFZ',
 35: 'AFF2',
 36: 'AFF4',
 37: 'AFF6',
 38: 'AFF8',
 39: 'AFF10',
 40: 'AFF9H',
 41: 'AFF7H',
 42: 'AFF5H',
 43: 'AFF3H',
 44: 'AFF1H',
 45: 'AFF2H',
 46: 'AFF4H',
 47: 'AFF6H',
 48: 'AFF8H',
 49: 'AFF10H',
 50: 'F9',
 51: 'F7',
 52: 'F5',
 53: 'F3',
 54: 'F1',
 55: 'FZ',
 56: 'F2',
 57: 'F4',
 58: 'F6',
 59: 'F8',
 60: 'F10',
 61: 'F9H',
 62: 'F7H',
 63: 'F5H',
 64: 'F3H',
 65: 'F1H',
 66: 'F2H',
 67: 'F4H',
 68: 'F6H',
 69: 'F8H',
 70: 'F10H',
 71: 'FFC9',
 72: 'FFC7',
 73: 'FFC5',
 74: 'FFC3',
 75: 'FFC1',
 76: 'FFCZ',
 77: 'FFC2',
 78: 'FFC4',
 79: 'FFC6',

In [22]:
raw_data["Fp1"]

(array([[0.00499397, 0.00500359, 0.00501654, ..., 0.00442987, 0.0044341 ,
         0.00444385]], shape=(1, 76032)),
 array([0.00000000e+00, 3.90625000e-03, 7.81250000e-03, ...,
        2.96988281e+02, 2.96992188e+02, 2.96996094e+02], shape=(76032,)))

In [37]:
window_data, window_mask = utils.mne_to_tensor(
    raw_data,
    normalize="window",
)

raw data shape torch.Size([127, 76032])
Skipping channel: TimestampS
Skipping channel: TimestampMs
Skipping channel: OrTimestampS
Skipping channel: OrTimestampMs
Skipping channel: Counter
Skipping channel: Interpolated
Skipping channel: RawCq
Skipping channel: Battery
Skipping channel: BatteryPercent
Skipping channel: FwBufferSize
Skipping channel: FwClockTime
Skipping channel: MarkerHardware
Skipping channel: CQ.Cz
Skipping channel: CQ.FCz
Skipping channel: CQ.Afz
Skipping channel: CQ.Fp1
Skipping channel: CQ.F5
Skipping channel: CQ.F1
Skipping channel: CQ.CP5
Skipping channel: CQ.CP3
Skipping channel: CQ.CP1
Skipping channel: CQ.P1
Skipping channel: CQ.P3
Skipping channel: CQ.P5
Skipping channel: CQ.P7
Skipping channel: CQ.PO7
Skipping channel: CQ.PO3
Skipping channel: CQ.O1
Skipping channel: CQ.Pz
Skipping channel: CQ.POz
Skipping channel: CQ.Oz
Skipping channel: CQ.O2
Skipping channel: CQ.PO4
Skipping channel: CQ.PO8
Skipping channel: CQ.P8
Skipping channel: CQ.P6
Skipping channel:

In [38]:
window_data.shape

torch.Size([297, 354, 256])

In [25]:
import torch
torch.allclose(rec_data, window_data)

False

In [26]:
rec_data - window_data

tensor([[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 5.9496,  6.0366,  6.1538,  ...,  1.5055,  1.5786,  1.6203],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         ...,
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 8.6251,  8.6176,  8.8159,  ...,  1.2841,  1.3926,  1.4300]],

        [[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [-0.5835, -0.2703,  0.0187,  ...,  1.0224,  1.0771,  1.1897],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         ...,
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0639,  0.1456,  0.2264,  ...,  0.3325,  0.3305,  0.3403]],

        [[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0165, -0.2347, -0.7621,  ...,  0

In [33]:
overlap_data, overlap_mask = utils.mne_to_tensor(
    raw_data,
    normalize="recording",
    overlap=0.5
)

raw data shape torch.Size([127, 76032])
Skipping channel: TimestampS
Skipping channel: TimestampMs
Skipping channel: OrTimestampS
Skipping channel: OrTimestampMs
Skipping channel: Counter
Skipping channel: Interpolated
Skipping channel: RawCq
Skipping channel: Battery
Skipping channel: BatteryPercent
Skipping channel: FwBufferSize
Skipping channel: FwClockTime
Skipping channel: MarkerHardware
Skipping channel: CQ.Cz
Skipping channel: CQ.FCz
Skipping channel: CQ.Afz
Skipping channel: CQ.Fp1
Skipping channel: CQ.F5
Skipping channel: CQ.F1
Skipping channel: CQ.CP5
Skipping channel: CQ.CP3
Skipping channel: CQ.CP1
Skipping channel: CQ.P1
Skipping channel: CQ.P3
Skipping channel: CQ.P5
Skipping channel: CQ.P7
Skipping channel: CQ.PO7
Skipping channel: CQ.PO3
Skipping channel: CQ.O1
Skipping channel: CQ.Pz
Skipping channel: CQ.POz
Skipping channel: CQ.Oz
Skipping channel: CQ.O2
Skipping channel: CQ.PO4
Skipping channel: CQ.PO8
Skipping channel: CQ.P8
Skipping channel: CQ.P6
Skipping channel:

In [34]:
overlap_data.shape

torch.Size([354])

In [16]:
import data.alljoined
importlib.reload(data.alljoined)

<module 'data.alljoined' from '/kreka/research/willy/side/brain/data/alljoined.py'>

In [17]:
a = list(data.alljoined.fetch_alljoined())

Malformed block directory /kreka/research/willy/side/alljoined/raw_eeg/sub-07/session_01/session_03, skipping...
Malformed block directory /kreka/research/willy/side/alljoined/raw_eeg/sub-07/session_01/session_02, skipping...
Malformed block directory /kreka/research/willy/side/alljoined/raw_eeg/sub-07/session_01/session_04, skipping...


In [18]:
a

[{'file': '/kreka/research/willy/side/alljoined/raw_eeg/sub-16/session_04/block_02/Subject 16, Session 4, Block 2 Recording_FLEX2_213075_2025.04.11T13.34.35.07.00.md.edf',
  'subject': 'alljoined::sub-16',
  'session': 'alljoined::sub-16::session_04',
  'block': 'alljoined::sub-16::session_04::block_02',
  'metadata': PosixPath('/kreka/research/willy/side/alljoined/raw_eeg/sub-16/session_04/block_02/Subject 16, Session 4, Block 2 Recording_FLEX2_213075_2025.04.11T13.34.35.07.00.json')},
 {'file': '/kreka/research/willy/side/alljoined/raw_eeg/sub-16/session_04/block_12/Subject 16, Session 4, Block 12 Recording_FLEX2_213075_2025.04.11T14.39.25.07.00.md.edf',
  'subject': 'alljoined::sub-16',
  'session': 'alljoined::sub-16::session_04',
  'block': 'alljoined::sub-16::session_04::block_12',
  'metadata': PosixPath('/kreka/research/willy/side/alljoined/raw_eeg/sub-16/session_04/block_12/Subject 16, Session 4, Block 12 Recording_FLEX2_213075_2025.04.11T14.39.25.07.00.json')},
 {'file': '/kr

In [19]:
len(a)

1525

In [20]:
import polars as pl
df = pl.from_dicts(a)

In [21]:
df

shape: (1_525, 5)
┌───────────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ file              ┆ subject           ┆ session           ┆ block             ┆ metadata         │
│ ---               ┆ ---               ┆ ---               ┆ ---               ┆ ---              │
│ str               ┆ str               ┆ str               ┆ str               ┆ object           │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ /kreka/research/w ┆ alljoined::sub-16 ┆ alljoined::sub-16 ┆ alljoined::sub-16 ┆ /kreka/research/ │
│ illy/side/all…    ┆                   ┆ ::session_04      ┆ ::session_04:…    ┆ willy/side/all…  │
│ /kreka/research/w ┆ alljoined::sub-16 ┆ alljoined::sub-16 ┆ alljoined::sub-16 ┆ /kreka/research/ │
│ illy/side/all…    ┆                   ┆ ::session_04      ┆ ::session_04:…    ┆ willy/side/all…  │
│ /kreka/research/w ┆ alljoined::sub-16 ┆ alljoined::sub-16 ┆ alljoined::sub-16 ┆ /kreka/research/ │
│ illy/side/all…    ┆                   ┆ ::session_04      ┆ ::session_04:…    ┆ willy/side/all…  │
│ /kreka/research/w ┆ alljoined::sub-16 ┆ alljoined::sub-16 ┆ alljoined::sub-16 ┆ /kreka/research/ │
│ illy/side/all…    ┆                   ┆ ::session_04      ┆ ::session_04:…    ┆ willy/side/all…  │
│ /kreka/research/w ┆ alljoined::sub-16 ┆ alljoined::sub-16 ┆ alljoined::sub-16 ┆ /kreka/research/ │
│ illy/side/all…    ┆                   ┆ ::session_04      ┆ ::session_04:…    ┆ willy/side/all…  │
│ …                 ┆ …                 ┆ …                 ┆ …                 ┆ …                │
│ /kreka/research/w ┆ alljoined::sub-02 ┆ alljoined::sub-02 ┆ alljoined::sub-02 ┆ /kreka/research/ │
│ illy/side/all…    ┆                   ┆ ::session_01      ┆ ::session_01:…    ┆ willy/side/all…  │
│ /kreka/research/w ┆ alljoined::sub-02 ┆ alljoined::sub-02 ┆ alljoined::sub-02 ┆ /kreka/research/ │
│ illy/side/all…    ┆                   ┆ ::session_01      ┆ ::session_01:…    ┆ willy/side/all…  │
│ /kreka/research/w ┆ alljoined::sub-02 ┆ alljoined::sub-02 ┆ alljoined::sub-02 ┆ /kreka/research/ │
│ illy/side/all…    ┆                   ┆ ::session_01      ┆ ::session_01:…    ┆ willy/side/all…  │
│ /kreka/research/w ┆ alljoined::sub-02 ┆ alljoined::sub-02 ┆ alljoined::sub-02 ┆ /kreka/research/ │
│ illy/side/all…    ┆                   ┆ ::session_01      ┆ ::session_01:…    ┆ willy/side/all…  │
│ /kreka/research/w ┆ alljoined::sub-02 ┆ alljoined::sub-02 ┆ alljoined::sub-02 ┆ /kreka/research/ │
│ illy/side/all…    ┆                   ┆ ::session_01      ┆ ::session_01:…    ┆ willy/side/all…  │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘