In [2]:
import sys
from pathlib import Path

sys.path.append(
    str(Path.cwd().parent)
)

In [3]:
import importlib
import data.builder
importlib.reload(data.builder)

<module 'data.builder' from '/kreka/research/willy/side/brain/data/builder.py'>

In [4]:
config = data.builder.DatasetConfig(
    name="test-alljoined"
)
config

DatasetConfig(name='test-alljoined', overlap=0.0, window_seconds=1.0, target_sfreq=256, normalization='recording', train_split=0.9, val_split=0.1)

In [5]:
from data.alljoined import fetch_alljoined


In [6]:
alljoined_files = list(fetch_alljoined())

Malformed block directory /kreka/research/willy/side/alljoined/raw_eeg/sub-07/session_01/session_03, skipping...
Malformed block directory /kreka/research/willy/side/alljoined/raw_eeg/sub-07/session_01/session_02, skipping...
Malformed block directory /kreka/research/willy/side/alljoined/raw_eeg/sub-07/session_01/session_04, skipping...


In [7]:
len(alljoined_files)

1525

In [8]:
rows = data.builder.load_file(
    config,
    alljoined_files[0]
)

Extracting EDF parameters from /kreka/research/willy/side/alljoined/raw_eeg/sub-16/session_04/block_02/Subject 16, Session 4, Block 2 Recording_FLEX2_213075_2025.04.11T13.34.35.07.00.md.edf...
Setting channel info structure...
Creating raw.info structure...
raw data shape torch.Size([127, 72960])
Skipping channel: TimestampS
Skipping channel: TimestampMs
Skipping channel: OrTimestampS
Skipping channel: OrTimestampMs
Skipping channel: Counter
Skipping channel: Interpolated
Skipping channel: RawCq
Skipping channel: Battery
Skipping channel: BatteryPercent
Skipping channel: FwBufferSize
Skipping channel: FwClockTime
Skipping channel: MarkerHardware
Skipping channel: CQ.Cz
Skipping channel: CQ.FCz
Skipping channel: CQ.Afz
Skipping channel: CQ.Fp1
Skipping channel: CQ.F5
Skipping channel: CQ.F1
Skipping channel: CQ.CP5
Skipping channel: CQ.CP3
Skipping channel: CQ.CP1
Skipping channel: CQ.P1
Skipping channel: CQ.P3
Skipping channel: CQ.P5
Skipping channel: CQ.P7
Skipping channel: CQ.PO7
Ski

In [9]:
len(rows)

285

In [10]:
rows[0]

{'sample': tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.2108, 0.0878, 0.0142,  ..., 0.2366, 0.3243, 0.4402],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.8981, 0.6632, 0.5431,  ..., 0.4177, 0.5113, 0.7621]]),
 'mask_indices': tensor([[  1],
         [  3],
         [ 52],
         [ 54],
         [ 56],
         [ 58],
         [ 97],
         [147],
         [198],
         [199],
         [200],
         [202],
         [203],
         [204],
         [247],
         [248],
         [249],
         [250],
         [251],
         [252],
         [253],
         [254],
         [255],
         [289],
         [291],
         [293],
         [295],
         [297],
         [331],
         [332],
         [333],
         [353]]),
 'idx': 0,
 'file': '/kreka/research/willy/side/alljoi

In [12]:
rows[0]["mask_indices"].shape

torch.Size([32, 1])

In [17]:
rows[0]["mask_indices"].squeeze()

tensor([  1,   3,  52,  54,  56,  58,  97, 147, 198, 199, 200, 202, 203, 204,
        247, 248, 249, 250, 251, 252, 253, 254, 255, 289, 291, 293, 295, 297,
        331, 332, 333, 353])

In [18]:
rows[0]["sample"].shape

torch.Size([354, 256])

In [19]:
rows[0]["sample"]

tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.2108, 0.0878, 0.0142,  ..., 0.2366, 0.3243, 0.4402],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.8981, 0.6632, 0.5431,  ..., 0.4177, 0.5113, 0.7621]])

In [20]:
from utils import NUM_CHANNELS

In [ ]:
def to_sparse(
    sample, mask
):
    pass

In [22]:
sample = rows[0]["sample"]

In [23]:
sample.shape

torch.Size([354, 256])

In [25]:
mask_indices = rows[0]["mask_indices"]

In [27]:
mask_indices.shape

torch.Size([32, 1])

In [28]:
mi = mask_indices.squeeze()
mi, mi.shape

(tensor([  1,   3,  52,  54,  56,  58,  97, 147, 198, 199, 200, 202, 203, 204,
         247, 248, 249, 250, 251, 252, 253, 254, 255, 289, 291, 293, 295, 297,
         331, 332, 333, 353]),
 torch.Size([32]))

In [33]:
import torch
recreated = torch.zeros(NUM_CHANNELS, dtype=torch.bool)
recreated[mi] = True
recreated, recreated.shape

(tensor([False,  True, False,  True, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False,  True, False,  True, False,  True, False,  True, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False,  True, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, F

In [36]:
sparse = sample[recreated]
sparse, sparse.shape

(tensor([[0.2108, 0.0878, 0.0142,  ..., 0.2366, 0.3243, 0.4402],
         [0.3717, 0.2368, 0.1785,  ..., 0.2531, 0.3523, 0.5404],
         [0.7670, 0.4657, 0.3268,  ..., 0.1430, 0.3012, 0.6281],
         ...,
         [0.4062, 0.2541, 0.1418,  ..., 0.1817, 0.2704, 0.4876],
         [0.3656, 0.2147, 0.1238,  ..., 0.2974, 0.3834, 0.5635],
         [0.8981, 0.6632, 0.5431,  ..., 0.4177, 0.5113, 0.7621]]),
 torch.Size([32, 256]))

In [35]:
dense = torch.zeros(
    NUM_CHANNELS,
    256
)

In [38]:
dense[recreated] = sparse
dense, dense.shape

(tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.2108, 0.0878, 0.0142,  ..., 0.2366, 0.3243, 0.4402],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.8981, 0.6632, 0.5431,  ..., 0.4177, 0.5113, 0.7621]]),
 torch.Size([354, 256]))

In [39]:
torch.allclose(dense, sample)

True

In [40]:
importlib.reload(data.builder)
rows = data.builder.load_file(
    config,
    alljoined_files[0]
)

Extracting EDF parameters from /kreka/research/willy/side/alljoined/raw_eeg/sub-16/session_04/block_02/Subject 16, Session 4, Block 2 Recording_FLEX2_213075_2025.04.11T13.34.35.07.00.md.edf...
Setting channel info structure...
Creating raw.info structure...
raw data shape torch.Size([127, 72960])
Skipping channel: TimestampS
Skipping channel: TimestampMs
Skipping channel: OrTimestampS
Skipping channel: OrTimestampMs
Skipping channel: Counter
Skipping channel: Interpolated
Skipping channel: RawCq
Skipping channel: Battery
Skipping channel: BatteryPercent
Skipping channel: FwBufferSize
Skipping channel: FwClockTime
Skipping channel: MarkerHardware
Skipping channel: CQ.Cz
Skipping channel: CQ.FCz
Skipping channel: CQ.Afz
Skipping channel: CQ.Fp1
Skipping channel: CQ.F5
Skipping channel: CQ.F1
Skipping channel: CQ.CP5
Skipping channel: CQ.CP3
Skipping channel: CQ.CP1
Skipping channel: CQ.P1
Skipping channel: CQ.P3
Skipping channel: CQ.P5
Skipping channel: CQ.P7
Skipping channel: CQ.PO7
Ski

In [45]:
rows[0]["sample"].shape

torch.Size([32, 256])

In [1]:
len(alljoined_files)

NameError: name 'alljoined_files' is not defined